#theme: jekyll-theme-minimal
#remote_theme: benbalter/retlab
remote_theme: pmarsceill/just-the-docs
#remote_theme: shawnday/minimal
title: Shawn Day
description: this is the personal website of shawn day
twitter_username: iridium
github_username:  shawnday
email: shawn.day@ucc.ie

plugins:
  - jekyll-feed
