#theme: jekyll-theme-minimal
remote_theme: benbalter/retlab
title: Shawn Day
description: this is the personal website of shawn day
twitter_username: iridium
github_username:  shawnday

plugins:
  - jekyll-feed
